### ISSUE TITLE
Change Bazel Java Builder template to latest version

### ISSUE THREAD

**Issue by LeonovecSergey** [salesforce/bazel-ls-demo-project#6]
Bazel build //... generates error: package mybuilder_sample_generation does not exist
There is no generated Java class in the folder.
https://github.com/salesforce/bazel-ls-demo-project/tree/last-version-generator

**Comment by guw** [comment]
There was a change some time ago. I wonder if this happened before or after I created the demo project. The source generator was modified to not just compile source code but also produce a jar file.

https://github.com/salesforce/bazel-java-builder-template/commit/ace1f070f87c675c8c7a7799ba2ccfb9e7f78562
